### ISSUE TITLE
Error case on namespace

### ISSUE THREAD

**Issue by webmezenc** [adrienrn/php-mimetyper#10]
Hi,

I have an error in namespace on RepositoryInterface.

`namespace Mimetyper\Repository;`

to

`namespace MimeTyper\Repository;`

Thanks for resolution of problem.

Best regards,
Jérémy

**Comment by adrienrn** [comment]
Thanks,
It shouldn't be a problem for the execution of the code but I will definitely fix it.

**Comment by adrienrn** [comment]
Fixed in tag 0.2.2

**Comment by adrienrn** [comment]
#12

**Comment by webmezenc** [comment]
Thanks, I detected this error in Symfony with an exception
